import type { Metadata } from 'next';
import './globals.css';
import { Navbar } from '@/components/navbar/navbar';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/providers/theme-provider';
import localFont from 'next/font/local';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const departure = localFont({
	src: '../fonts/DepartureMono-Regular.otf',
	display: 'swap',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn(departure.className, 'antialiased')}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Navbar />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
