import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import localFont from 'next/font/local';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const departure = localFont({
	src: '../fonts/DepartureMono-Regular.otf',
	display: 'swap',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(departure.className, 'antialiased')}>{children}</body>
		</html>
	);
}
